config/routes.rb
ProjectARhT::Application.routes.draw do

  devise_for :users, :path => 'user'
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end

  resources :users, :controller => "users" do
		post 'users/:id' => "users#update" 
		resource :clinic
		resources :client_sessions, :only => [:index]

	end
	
	resources :client_sessions

	resources :gestures do
		resources :classifiers do
			resources :gesture_samples, :except => ['edit', 'update']
		end
	end

	resources :classifiers

	namespace :api do
  	namespace :v1  do
  	  resources :tokens,:only => [:create, :destroy]
  	end
	end

	root :to => 'static#home'
end

app/models/clinic.rb
class Clinic < ActiveRecord::Base
	belongs_to :therapist, :class_name => "User"
	belongs_to :client, :class_name => "User"

	has_many :client_sessions, :select => ['sessions.created_at', :effort, :gesture_id]
	has_and_belongs_to_many :gestures, :select => [:id, :title, :description, :repetitions]

  def find_sessions_by_gesture(gesture_id_p)
    client_sessions.where(:clinic_id => id, :gesture_id => gesture_id_p)
  end

	def find_effort_by_gesture(gesture_id_p)
		@sessions = find_sessions_by_gesture(gesture_id_p)
		@effort = @sessions.map{ |k| {:created_at => k.created_at, :effort => k.effort}}
	end

	def find_rms_by_gesture(gesture_id_p)
		@sessions = find_sessions_by_gesture(gesture_id_p)
		@rms = @sessions.map{ |k| k.rms }
	end

end

app/controllers/clinics_controller.rb
class ClinicsController < ApplicationController
	load_and_authorize_resource

  # GET /clinics
  # GET /clinics.json
  def index
    @clinics = Clinic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clinics }
    end
  end

  # GET /clinics/1
  # GET /clinics/1.json
  def show
		@user = User.find(params[:user_id])
		@clinic = @user.inverse_clinic
		@sessions = @clinic.client_sessions
		@gestures = @clinic.gestures.select('gestures.title, gestures.id')
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sessions }
    end
  end

  # GET /clinics/new
  # GET /clinics/new.json
  def new
    @clinic = Clinic.new
		@gestures = Gesture.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @clinic }
    end
  end

  # GET /clinics/1/edit
  def edit
    @clinic = User.find(params[:user_id]).inverse_clinic
		@gestures = Gesture.all
  end

  # POST /clinics
  # POST /clinics.json
  def create
    @clinic = Clinic.new(params[:clinic])

    respond_to do |format|
      if @clinic.save
        format.html { redirect_to @clinic.client, notice: 'Clinic was successfully created.' }
        format.json { render json: @clinic, status: :created, location: @clinic.client }
      else
        format.html { redirect_to @clinic.client }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clinics/1
  # PUT /clinics/1.json
  def update
		@gestures = Gesture.all
		@user = User.find(params[:user_id])
    @clinic = @user.inverse_clinic
    respond_to do |format|
      if @clinic.update_attributes(params[:clinic])
        format.html { redirect_to user_path(@user), notice: 'Clinic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to user_path(@user) }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clinics/1
  # DELETE /clinics/1.json
  def destroy
    @clinic = Clinic.find(params[:id])
    @clinic.destroy

    respond_to do |format|
      format.html { redirect_to users_path }
      format.json { head :no_content }
    end
  end
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/views/clinics/_clinic.html.erb
<div id='clinic_information'>
	<%= render 'clinics/form', :object => clinic, :as => @clinic %>	
</div>

app/views/clinics/_form.html.erb
<script>
	$(function() {
		
var v = $( "#clinic_therapy_repetitions" ).val();
		$( "#clinic_therapy_repetitions_slider" ).slider({
			range: "min", 
			value: v,
			min: 1,
			max: 20,
			slide: function( event, ui ) {
				$( "#clinic_therapy_repetitions" ).val(ui.value );
			}
		});
		
	});

	</script>

<%= form_for(@clinic, :url => user_clinic_url(@user)) do |f| %>
  <% if @clinic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clinic.errors.count, "error") %> prohibited this clinic from being saved:</h2>
      <ul>
      <% @clinic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<div id='reminder_form'>
		<div class="field">
		  <%= f.label :therapy_repetitions %><br />
		  <%= f.text_field :therapy_repetitions, :in => 1...20%>
			<div style="width:30%;" id="clinic_therapy_repetitions_slider"></div>
		</div>
	</div>
	<%unless @clinic.gestures.empty? %>
		Assigned Excercises:
	<%else%>
		Assign Excercises:
	<%end%>
	<div id='gesture_checkboxes'>
		<% for gesture in @gestures %>
<div class="checkbox_wrapper">
				<%= check_box_tag "clinic[gesture_ids][]", gesture.id, @clinic.gestures.include?(gesture), :id => "gesture_checkboxes_id_"<<gesture.title %>
				<label for="<%="gesture_checkboxes_id_"<<gesture.title%>"><%= gesture.title %>
</div>
		<% end %>
	</div>
  <div class="actions">
    <%= f.submit 'Update Therapy Information' %>
  </div>
<% end %>

app/views/clinics/edit.html.erb
<h1>Editing clinic</h1>

<%= render 'form' %>

<%= link_to 'Back', user_clinic_path(@user) %>

app/views/clinics/index.html.erb
<h1>Listing clinics</h1>

<table>
  <tr>
    <th>Therapist</th>
    <th>Client</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clinics.each do |clinic| %>
  <tr>
    <td><%= clinic.therapist_id %></td>
    <td><%= clinic.client_id %></td>
    <td><%= link_to 'Show', clinic %></td>
    <td><%= link_to 'Edit', edit_clinic_path(clinic) %></td>
    <td><%= link_to 'Destroy', clinic, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Clinic', new_clinic_path %>

app/views/clinics/new.html.erb
<h1>New clinic</h1>

<%= render 'form' %>

<%= link_to 'Back', clinics_path %>

app/views/clinics/show.html.erb
<p id="notice"><%= notice %></p>

<%= javascript_include_tag '/javascripts/highcharts.js' %>
<%= javascript_include_tag '/javascripts/highcharts-exporting.js' %>

<h2><%=@user.title%></h2>
<%= link_to 'Edit/Back', user_path(@user) %>
<!-- the tabs -->
<div id="tabs" style="height:100%;padding:20px;">
	<ul>
		<%@gestures.each do |gesture|%>
			<li><a href="#statistics_<%=gesture.id%>"><%=gesture.title%></a></li>
		<% end %>
	</ul>
		<%@gestures.each do |gesture|%>
			<div id='statistics_<%=gesture.id%>' class='hc_cont' style="height:260px;"></div>
		<% end %>
</div>

<script type="text/javascript">
var chart;
jQuery(document).ready(function(){
	<% @str = Array.new %>
	<%@gestures.each do |gesture|%>
		<% @str << "chart(#{gesture.id}, '#{gesture.title}');" %>
	<% end %>
	<%= @str.join("\n\t") %>
});
function chart(gesture_id, title) {
	var options = {
		chart: {
			renderTo: 'statistics_'+gesture_id,
         zoomType: 'x',
         defaultSeriesType: 'column',
				width: 800
      },
      title: {
         text: title
      },
      subtitle: {
         text: 'Therapy Results'
      },
      xAxis: {
         type: 'datetime',
         dateTimeLabelFormats: { // don't display the dummy year
            month: '%e. %b',
            year: '%b'
         }
      },
      yAxis:
			[{ // Primary yAxis
				min: 0,
				max: 100,
				labels: {
					formatter: function() {
						return this.value +' %';
					},
					style: {
						color: '#00F'
					}
				},
				title: {
					text: 'Effort'
				},
				opposite: true

			}, { // Secondary yAxis
min: -50,
max:50,
				gridLineWidth: 0,
				title: {
					text: 'Variance',
					style: {
						color: '#920'
					}
				},
				labels: {
					formatter: function() {
						return this.value;
					},
					style: {
						color: '#920'
					}
				}

			}],
      legend: {
         layout: 'vertical',
         align: 'left',
         verticalAlign: 'top',
         x: 100,
         y: 70,
         floating: true,
         shadow: true
      },
      tooltip: {
         			formatter: function() {
					return '<b>'+ this.series.name +'</b><br/>'+
	 					this.y +' <br />' +
					Highcharts.dateFormat('%e %b, %l:%M %p', this.x);
				}
      },
      plotOptions: {
         column: {
            pointPadding: 0.2,
            borderWidth: 0
         }
      },
      series: [
				{name: 'effort'},
				{name: 'variance',
					yAxis:1,
					type:'spline',
					marker: {
						enabled: false
					},
					dashStyle: 'shortdot'}
				]
			};
 
			// Load data asynchronously using jQuery. On success, add the data
			 // to the options and initiate the chart.
			 // This data is obtained by exporting a GA custom report to TSV.
			 // http://api.jquery.com/jQuery.get/
				jQuery.getJSON('<%= user_client_sessions_path(@user, :format =>'json')%>?gesture_id='+gesture_id+'', function(data) {
					var effort = [];
					var variance = [];
					jQuery.each(data, function(key, value) {
						var mean_sum = 0;
						var max_val = 1;	


						for(var i = 0; i<value.length; i++){
							mean_sum = mean_sum + parseFloat(value[i].effort);
						}
						mean_sum /= (i+1);
						for(i = 0; i<value.length; i++){
							var d = new Date(value[i].created_at);
							var curr_minute = d.getMinutes();
							var curr_hour = d.getHours();
							var curr_date = d.getDate();
							var curr_month = d.getMonth(); //months are zero based
							var curr_year = d.getFullYear();
							//alert(max_val);
								var d = new Date()
								var n = d.getTimezoneOffset();
var msOffset = n*60*1000
							effort.push( [ Date.UTC(curr_year, curr_month, curr_date, curr_hour, curr_minute) +msOffset, value[i].effort] );
							variance.push( [ Date.UTC(curr_year, curr_month, curr_date, curr_hour, curr_minute) + msOffset , (value[i].effort-mean_sum)] );
					}
				});      

			options.series[0].data = effort;
			options.series[1].data = variance;
      chart = new Highcharts.Chart(options);
   });

	jQuery('#tabs').tabs();
}
</script>	