config/routes.rb
ProjectARhT::Application.routes.draw do

  devise_for :users, :path => 'user'
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end

  resources :users, :controller => "users" do
		post 'users/:id' => "users#update" 
		resource :clinic
		resources :client_sessions, :only => [:index]

	end
	
	resources :client_sessions

	resources :gestures do
		resources :classifiers do
			resources :gesture_samples, :except => ['edit', 'update']
		end
	end

	resources :classifiers

	namespace :api do
  	namespace :v1  do
  	  resources :tokens,:only => [:create, :destroy]
  	end
	end

	root :to => 'static#home'
end

app/models/user.rb
class User < ActiveRecord::Base
	ROLES = %w[ Client Therapist ]

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :token_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :surname

	has_many :clinics, :foreign_key => 'therapist_id', :dependent => :destroy
	has_many :clients, :through => :clinics, :order => [:surname, :name, :email]

	has_one :inverse_clinic, :class_name => 'Clinic', :foreign_key => 'client_id', :dependent => :destroy, :select => [:id, :therapy_start_hour, :therapy_start_minute, :therapy_repetitions, :therapy_repetition_interval]

	has_one :therapist, :through => :inverse_clinic

	validates :name, :presence => true, :length => {:minimum => 1}
	validates :surname, :presence => true, :length => {:minimum => 1}

  def self.therapists
    where(role: ROLES[1])
  end

	def therapist?
		!!(role == ROLES[1])
	end

  def self.clients
    where(role: ROLES[0])
  end

	def client?
		!!(role == ROLES[0])
	end

	def title
		if name.nil?
			email
		else
			 if surname.nil? || surname == ""
					name 
				else
				[ surname, name].join(", ")
			end
		end
	end
		
end

app/controllers/users_controller.rb
#user_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  
  def index
    @users = current_user.clients(:select => [:name, :surname, :email])
  end
  
	def show
		@user = User.find(params[:id])
		@clinic = @user.inverse_clinic(:select => [:id])
		@excercises = @clinic.gestures
		@gesture_samples = GestureSample.where("gesture_id IN (?)", @clinic.gesture_ids).order('gesture_id')
		@gestures = Gesture.all
	  respond_to do |format|
	    format.html
	    format.json { render :status=>200, :json => {:user => @user, :clinic => @clinic, :excercises => @excercises, :gesture_samples => @gesture_samples} }
	  end
	end

  def new
    @user = User.new
		render 'users/registrations/new'
  end
  
  def create
    @user = User.new(params[:user])
		@user.role = User::ROLES[0] #Defining as a client
    if @user.save
			@user.therapist = current_user #Adding to list of current therapist 
      flash[:notice] = "Successfully created User." 
      redirect_to user_path(@user)
    else
      render 'users/registrations/new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
		render 'users/registrations/edit'
  end
  
  def update
    @user = User.find(params[:id])
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?
    if @user.update_attributes(params[:user])
      flash[:notice] = "Successfully updated User."
      redirect_to users_path
    else
      render 'users/registrations/edit'
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "Successfully deleted User."
      redirect_to root_path
    end
  end
  
end

app/views/users/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/_user.html.erb
<tr>
	<td><%= link_to user.surname, user_path(user) %>   </td>
	<td><%= link_to user.name, user_path(user) %>      </td>
	<td><%= link_to 'Edit', edit_user_path(user) %>    </td>
	<td><%= link_to 'Delete', user_path(user), :method => 'delete' %>  </td>
</tr>

app/views/users/index.html.erb
<script type="text/javascript">
	jQuery(document).ready(function(){
        jQuery("#myTable").tablesorter( { 
        // sort on the first column and third column, order asc 
        sortList: [[0,0]] 
    	});
	}); 
</script>

<%= link_to 'New Client', new_user_path %>
<br />
<hr />

<table id="myTable" class="tablesorter">
	<thead>
		<tr>
			<th>
				Last Name
			</th>
			<th>
				First Name
			</th>
		</tr>
	</thead>
	<tbody>
<%= render :partial => 'user', :collection => @users%>
	</tbody>
</table>

app/views/users/show.html.erb
<script type="text/javascript">
	var chart;
	jQuery(document).ready(function(){
		jQuery("#tabs").tabs();	
	});
</script>

<h2><%=@user.title%></h2>
<div id="tabs">
	<ul>
		<li><a href="#home">User Home</a></li>
		<li><a href="#edit">Edit User</a></li>
	</ul>
	<div id="home">
		<%=link_to 'Show Therapy Results', user_clinic_path(@user)%><br />
		<%=link_to 'Edit User Registration', edit_user_path(@user)%><br />
		<%= link_to 'Back', users_path %>
	</div>
	<div id="edit">
		<%=render :partial => 'clinics/clinic', :object => @clinic, :@clinic => :clinic %>
	</div>
	</div>