config/routes.rb
ProjectARhT::Application.routes.draw do

  devise_for :users, :path => 'user'
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end

  resources :users, :controller => "users" do
		post 'users/:id' => "users#update" 
		resource :clinic
		resources :client_sessions, :only => [:index]

	end
	
	resources :client_sessions

	resources :gestures do
		resources :classifiers do
			resources :gesture_samples, :except => ['edit', 'update']
		end
	end

	resources :classifiers

	namespace :api do
  	namespace :v1  do
  	  resources :tokens,:only => [:create, :destroy]
  	end
	end

	root :to => 'static#home'
end

app/models/classifier.rb
class Classifier < ActiveRecord::Base
	has_many :gesture_samples
	has_many :gestures, :through => :gesture_samples
end

app/controllers/classifiers_controller.rb
class ClassifiersController < ApplicationController
	load_and_authorize_resource

  def index
		@classifiers = Classifier.find(:all)
		@gesture = Gesture.find(params[:gesture_id])
  end

  def new
		@classifier = Classifier.new
  end


  # POST /classifiers
  # POST /classifiers.json
  def create
    @classifier = Classifier.new(params[:classifier])

    respond_to do |format|
      if @classifier.save
        format.html { redirect_to root_url, notice: 'Classifier was successfully created.' }
        format.json { render json: @classifier, status: :created, location: @classifier }
      else
        format.html { render action: "new" }
        format.json { render json: @classifier.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
		@classifier = Classifier.find(params[:id])
  end

  # PUT /classifiers/1
  # PUT /classifiers/1.json
  def update
    @classifier = Classifier.find(params[:id])

    respond_to do |format|
      if @classifier.update_attributes(params[:classifier])
        format.html { redirect_to root_url, notice: 'Classifier was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @classifier.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /classifiers/1
  # DELETE /classifiers/1.json
  def destroy
    @classifier = Classifier.find(params[:id])
    @classifier.destroy

    respond_to do |format|
      format.html { redirect_to classifiers_url }
      format.json { head :no_content }
    end
  end
end

app/views/classifiers/_classifier.erb
<br />
<%= link_to classifier.title, gesture_classifier_gesture_samples_path(Gesture.find(params[:gesture_id]), classifier) %><br />
<%= link_to 'Edit', edit_gesture_classifier_path(Gesture.find(params[:gesture_id]), classifier) %><br />
<hr />

app/views/classifiers/_form.html.erb
<%= form_for(@classifier) do |f| %>
  <% if @classifier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@classifier.errors.count, "error") %> prohibited this classifier from being saved:</h2>

      <ul>
      <% @classifier.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/classifiers/edit.html.erb
<h1>Edit Classifier</h1>

<%= render 'form' %>

<%= link_to 'Back', classifiers_path %>

app/views/classifiers/index.html.erb
<%= link_to 'Edit '<<@gesture.title, edit_gesture_path(@gesture) %>

<%= link_to 'New Classifier', new_classifier_path %>
<hr />

<%= render :partial => 'classifier', :collection => @classifiers %>

<br />
<%= link_to 'Gestures', gestures_path %>

app/views/classifiers/new.html.erb
<h1>New Gesture</h1>

<%= render 'form' %>

<%= link_to 'Back', gestures_path %>

app/views/classifiers/show.html.erb
<%= render @classifier %>

<br />
<%= link_to 'Classifiers', classifiers_path %>