config/routes.rb
ProjectARhT::Application.routes.draw do

  devise_for :users, :path => 'user'
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end

  resources :users, :controller => "users" do
		post 'users/:id' => "users#update" 
		resource :clinic
		resources :client_sessions, :only => [:index]

	end
	
	resources :client_sessions

	resources :gestures do
		resources :classifiers do
			resources :gesture_samples, :except => ['edit', 'update']
		end
	end

	resources :classifiers

	namespace :api do
  	namespace :v1  do
  	  resources :tokens,:only => [:create, :destroy]
  	end
	end

	root :to => 'static#home'
end

app/models/gesture.rb
class Gesture < ActiveRecord::Base
	has_many :gesture_samples
	has_many :classifiers, :through => :gesture_samples
	has_many :client_sessions
	has_and_belongs_to_many :clinics

end

app/controllers/gestures_controller.rb
class GesturesController < ApplicationController
	load_and_authorize_resource

  def index
		@gestures = Gesture.find(:all)
  end

  def new
		@gesture = Gesture.new
  end


  # POST /gestures
  # POST /gestures.json
  def create
    @gesture = Gesture.new(params[:gesture])

    respond_to do |format|
      if @gesture.save
        format.html { redirect_to @gesture, notice: 'Gesture was successfully created.' }
        format.json { render json: @gesture, status: :created, location: @gesture }
      else
        format.html { render action: "new" }
        format.json { render json: @gesture.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
		@gesture = Gesture.find(params[:id])
  end

  # PUT /gestures/1
  # PUT /gestures/1.json
  def update
    @gesture = Gesture.find(params[:id])

    respond_to do |format|
      if @gesture.update_attributes(params[:gesture])
        format.html { redirect_to @gesture, notice: 'Gesture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gesture.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /gestures/1
  # DELETE /gestures/1.json
  def destroy
    @gesture = Gesture.find(params[:id])
    @gesture.destroy

    respond_to do |format|
      format.html { redirect_to gestures_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/gestures_helper.rb
module GesturesHelper
end

app/views/gestures/_form.html.erb
<%= form_for(@gesture) do |f| %>
  <% if @gesture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gesture.errors.count, "error") %> prohibited this gesture from being saved:</h2>

      <ul>
      <% @gesture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :repetitions  %><br />
    <%= f.number_field :repetitions %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gestures/_gesture.html.erb
<div id='gesture_information'>
<%= link_to gesture.title, gesture_classifiers_path(gesture) %><br />
<%= link_to 'Edit', edit_gesture_path(gesture) %>
</div>

app/views/gestures/edit.html.erb
<h1>Edit Classifier</h1>

<%= render 'form' %>

<%= link_to 'Back', classifiers_path %>

app/views/gestures/index.html.erb
<%= link_to 'New Gesture', new_gesture_path %>
<hr />

<%= render :partial => 'gesture', :collection => @gestures %>

<br />
<%=link_to 'Home', root_url %>

app/views/gestures/new.html.erb
<h1>New Gesture</h1>

<%= render 'form' %>

<%= link_to 'Back', gestures_path %>

app/views/gestures/show.html.erb
<%= render @gesture %>

<br />
<%= link_to 'Gestures', gestures_path %>